# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeNotas' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeNotas
  pod 'Firebase/Core'
  pod 'Firebase/Auth'  

  target 'ReactNativeNotas-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReactNativeNotasTests' do
    inherit! :search_paths
    # Pods for testing
  end

end